# pyproject.toml
[tool.poetry]
name = "pact-contract-testing"
version = "0.1.0"
description = "Pact contract testing setup"
authors = ["Your Name <your.email@example.com>"]
package-mode = false

[tool.poetry.dependencies]
python = "^3.13"
pact-python = "^1.5.0"
requests = "^2.31.0"
pytest = "^7.4.3"
pytest-cov = "^4.1.0"
pytest-mock = "^3.12.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
