name: Deploy Pact Broker

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 727646472452.dkr.ecr.us-east-1.amazonaws.com

      - name: Build and push Docker image
        run: |
          docker build -t pact-broker .
          docker tag pact-broker 727646472452.dkr.ecr.us-east-1.amazonaws.com/pact-broker:latest
          docker push 727646472452.dkr.ecr.us-east-1.amazonaws.com/pact-broker:latest

      - name: Install AWS CDK
        run: npm install -g aws-cdk

      - name: Install dependencies
        run: npm install

      - name: Deploy CDK Stack
        run: cdk deploy --require-approval never
